=== DustinGann/Web-Client-Applications/chapter13-1-dtd/assets/Schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
 
  <xs:element name="article">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="title"/>
        <xs:element type="xs:string" name="date"/>
        <xs:element name="author">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="firstName"/>
              <xs:element type="xs:string" name="lastName"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="summary"/>
        <xs:element type="xs:string" name="content"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== DustinGann/Web-Client-Applications/chapter13-1-dtd/main.xml
<?xml version = "1.0"?>

<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="/workspaces/Web-Client-Applications/chapter13-1-dtd/assets/Schema.xsd">

    <title>Simple XML</title>
    <date>July 4, 2007</date>
    <author>
        <firstName>John</firstName>
        <lastName>Doe</lastName>
    </author>
    <summary>XML is pretty easy.</summary>
    <content>This chapter presents examples that use XML.</content>
</article>
